### ISSUE TITLE
MFTF example throws error with OpenMDAO 3.1

### ISSUE THREAD

**Issue by shb84** [OpenMDAO/pyCycle#11]
This issue applies to pyCycle version 3.0. 
 
The mixed flow turbofan example "straight out of the box" yields the following error with OpenMDAO version 3.1: 

    ValueError: NewtonSolver in ChemEq (DESIGN.fc.conv.fs.totals.chem_eq): solve_subsystems must be set by the user

The example worked fine in OpenMDAO 2.8, after commenting out the line: 

    newton.options['reraise_child_analysiserror'] = False

**Comment by JustinSGray** [comment]
addressed in #19
