### ISSUE TITLE
Readme - Confusing pip install

### ISSUE THREAD

**Issue by onodip** [OpenMDAO/pyCycle#3]
The instruction for install can be a bit confusing, since there exists another _pycycle_ package:
https://github.com/bndr/pycycle/tree/master/pycycle

For me, even if I am in the correct folder, pip prefers to install the other _pycycle_.

I would propose to use one of the two options in the readme:

1.) 
Clone this repo, change directory to the pyCycle folder, then use pip to install:
`pip install .`

2.)
Use pip to install:
`pip install git+https://github.com/OpenMDAO/pyCycle.git`

**Comment by JustinSGray** [comment]
closed by #19
